### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by Bhaveshb292**

### CODE REVIEW

**Comment by Pietrob5** [comment]
@Bhaveshb292  If you can try adding this portion on top giving it more importance and writing more technical suff like that we used `tkinter` and that all "backend" functions are the same for GUI and CLI versions ecc. Thanks for contributing!

**Comment by Bhaveshb292** [comment]
i have added the changes you mentioned

**Review by Pietrob5 — APPROVED** [review]
I like it, clear and effective!

**Comment by Pietrob5** [comment]
@Bhaveshb292 do you know why you aren't among contibutors on this repository page?

**Pull request merged**
