### PR TITLE
Login window added 👍🏼

### PR DESCRIPTION
**Pull request by kun4LGit**
Login Screen

Added login window.
Fixed menu buttons.

I had a major issue where i changed the stuff as you said but the buttons lost their functionality only F9 was working.
I was not even getting any errors so even i was lost and unable to figure out and had to find other way to approach and solve the problem.
Usually this is among few reasons i dont prefer nest functions in tkinter it bugs at later stage and limits from adding any major features. Also the change we are trying to implement should have been planned at early stage.

But no worries i had other plan already just another way around by putting a separate login window instead.
The app starts with all the buttons in disabled state and gives a window to login and will only enable if the login is success then everything is normal in main window as usual :)
For now just have to press Submit or Register and you will be inside as the logic does nothing. But have commented the code where the if else should be.

### CODE REVIEW

**Comment by Pietrob5** [comment]
Thanks. Is it possible to put the login form on the main windows instead of creating a new windows?

**Review by Pietrob5 — COMMENTED** [review]
i really like this
`root.destroy()`
All the code is good, does what I asked.Thanks!

**Comment by Pietrob5** [comment]
I added all the backand for login and reister, now the app is basically finished. Tomorrow I'add the new .exe so that you can test it

**Comment by Pietrob5** [comment]
> I added all the backand for login and reister, now the app is basically finished. Tomorrow I'add the new .exe so that you can test it

if you are on Windows you can download and open pm_gui.exe to use the application. Test it creating new accounts, saving password (if you don't trust it jus save fake ones 😄). Test also how it handles wrong input form the users, if there are any bugs etc...
Let me know if you like it!

**Comment by kun4LGit** [comment]
> > I added all the backand for login and reister, now the app is basically finished. Tomorrow I'add the new .exe so that you can test it
> 
> if you are on Windows you can download and open pm_gui.exe to use the application. Test it creating new accounts, saving password (if you don't trust it jus save fake ones 😄). Test also how it handles wrong input form the users, if there are any bugs etc... Let me know if you like it!

Just bit busy but will sure check out the app and also try to find out some minor bugs and fix if needed..

BTW i was hoping can you explain how the app works compared to before when it use to make db locally. (which files exactly do what?)
Does it make an API call or just have some direct connection to db in cloud ? 
Did you had to pay for cloud service ?
How are are the user and password stored along with other data like service email ?
Im asking all this stuff cause i hope the knowledge comes in handy if in future i want to store some similar data through app or website.
If possible you can use "https://excalidraw.com/" to explain visually also.

**Comment by Pietrob5** [comment]
image

hopefully this helps understanding how it works. 
For Aiven I read it's documentation, expecially I followed this code to create a connection: https://aiven.io/docs/products/mysql/howto/connect-with-python
If you have any doubts just let me know. If you want I can add you on discord.

**Comment by kun4LGit** [comment]
> hopefully this helps understanding how it works. For Aiven I read it's documentation, expecially I followed this code to create a connection: https://aiven.io/docs/products/mysql/howto/connect-with-python If you have any doubts just let me know. If you want I can add you on discord.

Thank You
Here is my discord ID : kun4L#5225

**Comment by Pietrob5** [comment]
> Here is my discord ID : kun4L#5225

Sent, my name is Пьетро (I'm not Russian)

**Comment by kun4LGit** [comment]
> > Here is my discord ID : kun4L#5225
> 
> Sent, my name is Пьетро (I'm not Russian)

Done 👍🏼 And its cool dont matter where are you from. 
I come from a land where the person within matters... 🙏🏼🙂

**Pull request merged**
