### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kun4LGit**
Add Credentials was taking empty entries solved from GUI side.  Now no blank inputs will go through beside Note.
Solved:
prob1

### CODE REVIEW

**Comment by Pietrob5** [comment]
@kun4LGit  This is great thanks. Now if you want focus on service 2, 3 and 4 creating command for this
```
menuButton2 = Button(menuButtons, text='Search a Password', height=2, width=15).place(relx=0.2, rely=0.5, anchor=CENTER)
menuButton3 = Button(menuButtons, text='Modify a Password', height=2, width=15).place(relx=0.3, rely=0.5, anchor=CENTER)
menuButton4 = Button(menuButtons, text='Delete a Password', height=2, width=15).place(relx=0.4, rely=0.5, anchor=CENTER)
```
I'm working on checking for errors and handling every case of different inputs from users (just try not to work on the same issue)

**Review by Pietrob5 — COMMENTED** [review]
I like comments where you explain your choices 
`addCreds() # <- is always better idea than default as it helps user in adding multiple entries one after other`
this part also is very smart

**Comment by Pietrob5** [comment]
> I like comments where you explain your choices `addCreds() # <- is always better idea than default as it helps user in adding multiple entries one after other` this part also is very smart

Also, I've already added the same check to avoid null inputs to Search by Email, Delete All Database and View All Database, so you don't have to.

**Comment by kun4LGit** [comment]
> @kun4LGit This is great thanks. Now if you want focus on service 2, 3 and 4 creating command for this
> 
> ```
> menuButton2 = Button(menuButtons, text='Search a Password', height=2, width=15).place(relx=0.2, rely=0.5, anchor=CENTER)
> menuButton3 = Button(menuButtons, text='Modify a Password', height=2, width=15).place(relx=0.3, rely=0.5, anchor=CENTER)
> menuButton4 = Button(menuButtons, text='Delete a Password', height=2, width=15).place(relx=0.4, rely=0.5, anchor=CENTER)
> ```
> 
Yes no worries..

> I'm working on checking for errors and handling every case of different inputs from users (just try not to work on the same issue)

OK, Im anyhow not going to touch or do any changes to main functions.

> Also, I've already added the same check to avoid null inputs to Search by Email, Delete All Database and View All Database, so you don't have to.

Cool 👍 
Its always best practice to to stop user from putting such inputs from GUI too and making unnecessary main function calls.

> > I like comments where you explain your choices `addCreds() # <- is always better idea than default as it helps user in adding multiple entries one after other` this part also is very smart
> 

:)

**Pull request merged**
