### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kun4LGit**
There is a issue with the newly added copy button dont think it can be centered when we are getting multiple result like viewall or with scroll bar. Would suggest we drop the feature.
I had already done lot of work pre copy button update. 
- Added keybindings support from keys F1 till F9 Each function key will toggle the buttons above.. 
- Added Enter key support to many entry boxes upon clicking it will invoke the submit functions automatically. 
- Centered ViewAll display result.
- Cleaned unwanted commented code. 
- Delete Database dont seem to work dont know why..

Its almost done if we go pre copybutton code.
Just have to update documentation and icon thats it.

### CODE REVIEW

**Comment by Pietrob5** [comment]
> Added keybindings support from keys F1 till F9 Each function key will toggle the buttons above.. Added Enter key support to many entry boxes upon clicking it will invoke the submit functions automatically

Very good ideas, I was about to do that. Really appreciated!

> Delete Database dont seem to work dont know why

To me it works, does it give error to you?

I'd like to merde your Pull Request but there are conflicts with my modifications. Can you make the same changes (F1-F9, enter to submit and center text) on the new code I uploaded this morning? Is it easy and fast or too long? 

image
This is the problem and solve the conflict is very tedious. I'd be gratefull if you could add those functions to the new code. Thank you very much!!

**Comment by kun4LGit** [comment]
> To me it works, does it give error to you?
> 
> I'd like to merde your Pull Request but there are conflicts with my modifications. Can you make the same changes (F1-F9, enter to submit and center text) on the new code I uploaded this morning? Is it easy and fast or too long?
> 

I made changes before you added the copy button update to main and that copy button is already giving lots of problems to center (which i already solved in current code) is it possible to skip the copy feature ? 
If you run the code with previous update we are all good to go all GUI bugs are solved and features are working too we just have to add icon and update documentation thats it.

**Comment by Pietrob5** [comment]
@kun4LGit Actually I'd rather have Copy button than have the text centered. It's way to usefull and it makes no sense to get rid of it in my opinion. Just skip the part of centering the text, If you can add again on the new code F1-F9 and Enter key interaction it would be amazing!

**Comment by kun4LGit** [comment]
> @kun4LGit Actually I'd rather have Copy button than have the text centered. It's way to usefull and it makes no sense to get rid of it in my opinion. Just skip the part of centering the text, If you can add again on the new code F1-F9 and Enter key interaction it would be amazing!

Lots of things will break as i saved these changes for last but i will try..
Just dont change anything in gui till i put request many changes are dependent on each other so i have to go through everything again..

**Comment by Pietrob5** [comment]
> Just dont change anything in gui

I won't. You can copy the lines of code we need from old to new pm_gui.py. I'd like you to do this because you know which line are important to do what and which are useless so you'll be way faster than me

**Pull request closed without merging**
