### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kun4LGit**
- Fixed Buttons 😉🙂
- Added Icon (Can be changed to anything you like) Just rename it icon
- Fixed F2 (was not working)

I have increased the height (3) of buttons but dont know which looks good you can change it to previous height (2) also and it will still fit without problem.
See image for example.

Button Fix

### CODE REVIEW

**Review by Pietrob5 — APPROVED** [review]
Actually I didn'e evev tought about making the buttons taller, I just made them wider which ruined the view. I tied to add an icon but I failed, so if yours york it's super cool

**Comment by kun4LGit** [comment]
> Actually I didn'e evev tought about making the buttons taller, I just made them wider which ruined the view. I tied to add an icon but I failed, so if yours york it's super cool

You have to set proper limit to the text wrap so the F key comes on next line as you can see it will fit even on previous size.
You can download any icon i just took from google fonts to put it as a place holder for time being :)

**Comment by Pietrob5** [comment]
> You can download any icon i just took from google fonts to put it as a place holder for time being :)

the problem with the icon is that you have to add the path to the image, so adding `file = r'../Password-Manager/icon.png'` will work only for those who clone the repository. I'll try to handle the error when it doesn't find the images so that the program doesn't crash. -- I fixed it with `try: except:`

**Comment by kun4LGit** [comment]
> > You can download any icon i just took from google fonts to put it as a place holder for time being :)
> 
> the problem with the icon is that you have to add the path to the image, so adding `file = r'../Password-Manager/icon.png'` will work only for those who clone the repository. I'll try to handle the error when it doesn't find the images so that the program doesn't crash. -- I fixed it with `try: except:`

Oh i use some CLI tool to make app exe and i had similar problem about what you are trying to say i just zippped and had icon file in it. But later i found this GUI version dont know if you are using this to make exe but in this you can add files also i think even have a db file already present. You can also have main exe icon with your selected logo.
https://pypi.org/project/auto-py-to-exe/

**Comment by Pietrob5** [comment]
As I wrote in the README.md I used pyinstaller to generate .exe. I'll look also your suggestion

**Pull request merged**
