### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kun4LGit**
Added progress bar to `searchPassword_func(*args)`, `printCreditCard(*args)` and `searchByEmail(*args)`

### CODE REVIEW

**Comment by Pietrob5** [comment]
I ran your code but the animation doesn't show (my test database in quite big so for Find by Email takes a couple of seconds so it should be visible). Am I doing something wrong?

**Comment by kun4LGit** [comment]
> I ran your code but the animation doesn't show (my test database in quite big so for Find by Email takes a couple of seconds so it should be visible). Am I doing something wrong?

You will have to put threading in all those searches too. Like printall it should work then.
I thought the searchPassword_func(*args), printCreditCard(*args) and searchByEmail(*args) do search in different way thats why it is fast compared to printall.
I have a very small DB for testing with just few entries.
I really dont know how to use threading :(

**Comment by Pietrob5** [comment]
If you can add threading to all 4 functions. It's not a problem to have 4 threads, they are not concurrent. Thanks!

**Comment by kun4LGit** [comment]
> If you can add threading to all 4 functions. It's not a problem to have 4 threads, they are not concurrent. Thanks!

I dont have any idea about threading still i did tried but failed many times cant seem to get it running.
But i know for sure its like printall in old time pre threading where it use to stop and direct skip to result.
If you add threading to this i have already placed the progress where it needs to be.

**Comment by Pietrob5** [comment]
I added the animation to `searchByEmail`. Let me know if it works.

**Comment by kun4LGit** [comment]
> I added the animation to `searchByEmail`. Let me know if it works.

Cool.. I still dont know how it works and why it wont work in single thread but im glad it works. 
I tested it with time.sleep since my db file is small but i was able to see the animation.. 👍🏼

**Comment by Pietrob5** [comment]
> Cool.. I still dont know how it works and why it wont work in single thread but im glad it works.

i doesn't work because in single thread CPU can only do one thing at the time, so if it's running the function from pm.py it can't work on the animation. Thread let CPU do more work at the same time

**Comment by kun4LGit** [comment]
> > Cool.. I still dont know how it works and why it wont work in single thread but im glad it works.
> 
> i doesn't work because in single thread CPU can only do one thing at the time, so if it's running the function from pm.py it can't work on the animation. Thread let CPU do more work at the same time

BTW i just found out that my master password is not matching but when i checked with last commit it works. 👍🏼

**Comment by Pietrob5** [comment]
image
It works fine

**Comment by kun4LGit** [comment]
> image It works fine

In viewall or any other search.
But if i make new db i think it should fix

**Comment by Pietrob5** [comment]
What is your problem?

**Comment by kun4LGit** [comment]
> What is your problem?

I think its not updating / working because there was some changes made to key in pm and the current db was made using old key method
Should i delete and make new db ? I think it will fix the issue..

Untitled

**Comment by Pietrob5** [comment]
Yes, I changed some encription settings, so you have to delete the database and start a new one

**Comment by kun4LGit** [comment]
> Yes, I changed some encription settings, so you have to delete the database and start a new one

No problem will make new db, Just wanted to make sure and update you :)

**Comment by Pietrob5** [comment]
@kun4LGit Hi, I'm about to push some big changes. I moved the database to an online server with Aiven. Now I can acces it from every device. To do so I modified all functions in pm.py. Now you can't use it because you don't have keys for the server, but you can always use the old version of pm.py or create your database on Aiven and modify `create_connection()`.
Next step is to create a login/signup page, can you help me?
I'd like to add an inital page that shows when you open the page. It asks for username and master password and once you click Login or Signup it redirects you to the mainframe with the 9 buttons on top (the tab you did that used to be homepage). All clear?
For the moment by pushing Login or Signup buttons it just redirects you to homepage, later I'll add all login functions ecc. I've already made a draft of login windows, but couldn' place it at the beginnign and make it dissapear then, hopefully you can do it. 
image

Let me know if you can help with this.
Thanks 👍🏻

**Comment by kun4LGit** [comment]
> Let me know if you can help with this. Thanks 👍🏻

Only if i know we were going to go online authentication before i would have left some dummy login page with old previous DB we had.
It will take sometime to think of implementing few ides but im sure we can do some work around. 
The only problem is i dont know how the new online server works for example if i open app for first will it make a db on server like it use to make locally before ? 
And how will the user register for username so its not just login we will have to make user register too with some username email and master password.. 
Can you explain those 2 parts ?

**Comment by Pietrob5** [comment]
At the moment there is only one database, but with login I want to have more. When a user presses Signup the program register the user in USERS database and chreate "database-username" where passwords and cards will be stored. 
This is a scheme I made that explains more or less how it's going to work.
login

Now don't worry about it. You can just implement the frontend and graphical side of this part of the app, then I'll build the functions. At the moment the login form that you are making is useless, doesn't comunicate with the server. Pressing Login or Sigup it should redirect me to the homepage without doing anything else with the inputs of the user. I'll implement this in a sencond time.
All clear?

**Comment by kun4LGit** [comment]
> Now don't worry about it. You can just implement the frontend and graphical side of this part of the app, then I'll build the functions. At the moment the login form that you are making is useless, doesn't comunicate with the server. Pressing Login or Sigup it should redirect me to the homepage without doing anything else with the inputs of the user. I'll implement this in a sencond time. All clear?

Ok i thought the login is working.. 
But since its only gui should be ok i think i can open it directly.. 
Just dont do any changes to gui till i update. 👍🏼 

Also, What entry you want in register ? 
only username and masterpass ?

**Comment by Pietrob5** [comment]
> Also, What entry you want in register ?
> only username and masterpass ?

yes, something like this
image
If you want I can push this last modification with the 2 buttons. Let me know

**Comment by kun4LGit** [comment]
> > Also, What entry you want in register ?
> > only username and masterpass ? 
>If you want I can push this last modification with the 2 buttons. Let me know

No dont push i already made them :)

**Pull request closed without merging**
