### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by kun4LGit**
Search Password #Button 2 
Added functionality working now.

### CODE REVIEW

**Comment by Pietrob5** [comment]
@kun4LGit Hi! I've tested functionalities 2 and 3. Password Shearch works quite  well, I found only two small promblems that I'll fix myself: 

- `pm.get_mails` returns a list with more than one account for each service (I can have more tha one Gmail account for example) and in `searchPassword_func()` I'll add a for cicle to show all account and not just the first.
- In case of service not found it Exceptions are not handled

Those are just small bugs, nothing too problematic.
However for Modify a Password it seems to not be finished or it doesn't work at all. Am I doing something wrong or do you agree with me? Thank you for your contribution!!

**Review by Pietrob5 — APPROVED** [review]
I don't know why but GitHub doesn't show what you changed, but it says you deleted everithing and then pasted new code. In that way I can't quite see every modification to the code. I like how you followed my stile for coding and interfacintg with pm.py functions.

**Comment by Pietrob5** [comment]
@kun4LGit I added the possibility to delete a password, so the last things remaning are Modify an Entry and sone aesthetic and graphic embellishments. For example I really like that you added `header_Label`. It'd be really nice if the resut text printed in windows like View Database, Find by Email ecc could be centered orizzontally, since at the moment is alligned on the left. 

image
As you can see is not centered at all. Thank you!

**Comment by kun4LGit** [comment]
> Those are just small bugs, nothing too problematic. However for Modify a Password it seems to not be finished or it doesn't work at all. Am I doing something wrong or do you agree with me? Thank you for your contribution!!

The `def modify_entry` function should return something like a list [] it will be better. Just like print all 
As of now nothing is being returned by the function..


> It'd be really nice if the resut text printed in windows like View Database, Find by Email ecc could be centered orizzontally, since at the moment is alligned on the left.

I will get it center and make it more organized :)
But I have doubt in this thats why i kept it on hold, 
Do you want to print everything ? 
Error in decrtpting for service Or Only the service which matched.. 
Example : if i have total 5 entries in db and if my result is on 2nd then it still loops through everything instead of breaking and we have to wait till the whole search is complete the more entries in db the more waiting.. 
Is there anyway to fast search like indexing in db or do some DSA level of search sorry im weak in those topics but just suggestion.
Untitled-2024-08-14-1744

Also dont worry if you want to keep it like this 👆🏼 
I have another trick / idea in GUI i think it might work. 😉 
I will try to display some searching.. or progress till the whole db is scanned so the GUI wont feel as it hanged up. 👍🏼😃 

> I don't know why but GitHub doesn't show what you changed, but it says you deleted everithing and then pasted new code. In that way I can't quite see every modification to the code. I like how you followed my stile for coding and interfacintg with pm.py functions.

Maye be cause i copy the file then upload it directly instead of using cmd 🤔 

> Thank you for your contribution!!

Always Welcome just trying my best :)

**Comment by Pietrob5** [comment]
> I will try to display some searching.. or progress till the whole db is scanned so the GUI wont feel as it hanged up. 👍🏼😃

this is a great idea. I'd like to leave it as it is. If you use the same master password for all the entries then it should give either all correct results or all error message to let the user know they inputed the wrong master password. But you're right and it takes some secons to decrypt all passwords, so it''d be cool to add a progress bar or something like that (or percentage of loading or just some animation 
image
)

**Comment by kun4LGit** [comment]
> > I will try to display some searching.. or progress till the whole db is scanned so the GUI wont feel as it hanged up. 👍🏼😃
> 
> this is a great idea. I'd like to leave it as it is. If you use the same master password for all the entries then it should give either all correct results or all error message to let the user know they inputed the wrong master password. But you're right and it takes some secons to decrypt all passwords, so it''d be cool to add a progress bar or something like that (or percentage of loading or just some animation image )

Its bit hard and tricky but I will try my best and hope i can do something to show that search + application is active..
For now im just focused on getting those view all result in center there seem to be some issue or mistake with the placement i cannot figure i guess it has to do something with canvas and scrollbar may be 🤔 
Other results are fixed will upload together..

>Modify a Password it seems to not be finished or it doesn't work at all. Am I doing something wrong or do you agree with me? Thank you for your contribution!!

Please check `def modify_entry ` and make the function return list [] or something. Just like print all.
As of now nothing is being returned by the function. Thats why its not finished.

**Comment by Pietrob5** [comment]
> Please check def modify_entry  and make the function return list [] or something. Just like print all.
As of now nothing is being returned by the function. Thats why its not finished.

Why do you want it to return a list? I think it should just return 1 or 0 to notify fail or success and no other info. From pm_gui.py we can collect old and new credentials and use them to call `pm.modify_entry`. Then, if it returns 0 then everithing worked ok, else there were some problems. Do you agree with me?
Less important, Old Note input is useless, we can get rid of it.
image

**Comment by Pietrob5** [comment]
@kun4LGit 

> I think it should just return 1 or 0 to notify fail or success and no other info. From pm_gui.py we can collect old and new credentials and use them to call pm.modify_entry. Then, if it returns 0 then everithing worked ok, else there were some problems.

I pushed a new version implementing what I was saying here. Please test all 7 functions in the program and tell me for any bugs, mistake or improvements. For sure there's something I didn't think of. Then we'll focus on making it a bit more graphically nice. Thak you!

**Pull request merged**
